---
title: "In-Class Exercise 2: Geospatial Data Wrangling"
date: "16 Jan 2023"
date-modified: "`r Sys.Date()`"
number-sections: true
format: html
execute: 
  echo: true
  eval: true
  warning: false
editor: visual
---

# In-Class Exercise 2

## Creating Simple Features

### Aspatial Data

```{r}
pacman::p_load(sf, tidyverse, funModeling)
```

Importing WPdx+ (Nigeria) data set

```{r}
wp_nga <- read_csv("data/aspatial/wpdx.csv")
```

Creating Feature Data Frame for WPDX

```{r}
wp_nga$Geometry = st_as_sfc(wp_nga$`New Georeferenced Column`)
```

```{r}
wp_nga
```

```{r}
wp_sf <- st_sf(wp_nga, crs = 4326)
wp_sf
```

### Geospatial Data

Both sets of geospatial data are imported with the correct CRS of 26392.

```{r}
geoNGA = st_read(dsn="data/geospatial/geoboundaries_nga", 
                 layer = "geoBoundaries-NGA-ADM2") %>%
  st_transform(crs = 26392)
```

```{r}
NGA <- st_read("data/geospatial/NGA_cnty_admin2",
               layer = "nga_polbndl_adm2_1m_salb") %>%
  st_transform(crs = 26392)
```

## Geospatial Data Cleaning

```{r}
NGA <- NGA %>%
  select(c(3:4, 8:9))
```

## LGA Level

```{r}
wpdx_sf %>%
  group_by(water_source_clean) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
```

## Combining Geospatial and Aspatial Data Frames into Simple Feature Data Frame

## Distribution of Water Points
