project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
        - href: handson_ex/HE1/HE1.qmd
          text: Exercise 1
        - href: handson_ex/HE3/HE3.qmd
          text: Excercise 3
        - href: handson_ex/HE4/HE4.qmd
          text: Exercise 4
        - href: handson_ex/HE6/HE6.qmd
          text: Exercise 6
        - href: handson_ex/HE7/HE7.qmd
          text: Exercise 7
        - href: handson_ex/HE8/HE8.qmd
          text: Exercise 8
        - href: handson_ex/HE9/HE9.qmd
          text: Exercise 9
        - href: handson_ex/HE10/HE10.qmd
          text: Exercise 10
        - href: handson_ex/HE11/HE11.qmd
          text: Exercise 11
      - text: In-class Exercises
        menu: 
          - href: inclass_ex/ICE2/ice2.qmd
            text: Exercise 2
          - href: inclass_ex/ICE3/ice3.qmd
            text: Exercise 3
          - href: inclass_ex/ICE5/ICE5.qmd
            text: Exercise 5
          - href: inclass_ex/ICE6/ICE6.qmd
            text: Exercise 6
          - href: inclass_ex/ICE7/ICE7.qmd
            text: Exercise 7
          - href: inclass_ex/ICE9/ICE9.qmd
            text: Exercise 9
          - href: inclass_ex/ICE10/ICE10.qmd
            text: Exercise 10
      - text: Take-Home Exercises
        menu: 
          - href: take_home_ex/THE1/THE1.qmd
            text: Exercise 1
          - href: take_home_ex/THE2/THE2.qmd
            text: Exercise 2
          - href: take_home_ex/THE3/THE3.qmd
            text: Exercise 3
    right: 
      - href: index.qmd
        text: Home
      - href: https://github.com/bellekwang/IS415
        text: Github

format:
  html:
    theme: litera
    max-width: 80%
    css: styles.css
    toc: true

editor: visual

