project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
        - href: handsonex1.qmd
          text: Hands-on Exercise 1
        - href: handson_ex/HE3/HE3.qmd
          text: Hands-on Excercise 3
      - text: In-class Exercises
        menu: 
          - href: inclass_ex/ICE2/ice2.qmd
            text: In-class Exercise 2
          - href: inclass_ex/ICE3/ice3.qmd
            text: In-class Exercise 3
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

