project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
      - href: handsonex.qmd
        text: Hands-on Exercise
      - href: ice.qmd
        text: In-class Exerise
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

