---
title: "Hands-on Exercise 3: Cloropleth Mapping with R"
date: "`r Sys.Date()`"
---

```{r}
pacman::p_load(sf, tmap, tidyverse)
```

### Importing Data

Importing Geospatial Data

```{r}
mpsz <- st_read(
  dsn='data/geospatial',
  layer='MP14_SUBZONE_WEB_PL'
)
```

```{r}
mpsz
```

Importing Attribute Data

```{r}
popdata <- read_csv('data/aspatial/respopagesextod2011to2020.csv')
```

### Data Wrangling

```{r}
popdata2020 <- popdata %>%
  filter(Time == 2020) %>%
  group_by(PA, SZ, AG) %>%
  summarise(`POP` = sum(`Pop`)) %>%
  ungroup()%>%
  pivot_wider(names_from=AG, 
              values_from=POP) %>%
  mutate(YOUNG = rowSums(.[3:6])
         +rowSums(.[12])) %>%
mutate(`ECONOMY ACTIVE` = rowSums(.[7:11])+
rowSums(.[13:15]))%>%
mutate(`AGED`=rowSums(.[16:21])) %>%
mutate(`TOTAL`=rowSums(.[3:21])) %>%  
mutate(`DEPENDENCY` = (`YOUNG` + `AGED`)
/`ECONOMY ACTIVE`) %>%
  select(`PA`, `SZ`, `YOUNG`, 
       `ECONOMY ACTIVE`, `AGED`, 
       `TOTAL`, `DEPENDENCY`)
```

### Joining Attribute and Geospatial Data

```{r}

```
